name: fastapi-otel-elk

include:
  - ./docker-elk/docker-compose.yml
  - ./docker-elk/extensions/fleet/fleet-compose.yml
  - ./docker-elk/extensions/fleet/agent-apmserver-compose.yml

services:
  pets-api:
    container_name: pets-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DYNACONF_OTEL_ENDPOINT=http://apm-server:8200
      - DYNACONF_OTEL_BEARER_TOKEN="""
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - elk
    command: sh -c "poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
